'use client';

import { useState, useRef } from 'react';
import { FileUp, Sparkles, ChevronRight, Loader2 } from 'lucide-react';
import { generateStoryboardFromMemoir } from '@/app/actions/geminiActions';

interface Scene {
  index: number;
  title: string;
  description: string;
  mood: string;
}

export default function PdfToMangaPage() {
  const [step, setStep] = useState<'upload' | 'mapping' | 'preview'>('upload');
  const [file, setFile] = useState<File | null>(null);
  const [numScenes, setNumScenes] = useState(8);
  const [isProcessing, setIsProcessing] = useState(false);
  const [scenes, setScenes] = useState<Scene[]>([]);
  const fileInputRef = useRef<HTMLInputElement>(null);

  const handleFileUpload = (e: React.ChangeEvent<HTMLInputElement>) => {
    const selectedFile = e.target.files?.[0];
    if (selectedFile && selectedFile.type === 'application/pdf') {
      setFile(selectedFile);
      setStep('mapping');
    } else {
      alert('Please select a PDF file');
    }
  };

  const handleExtractAndGenerate = async () => {
    if (!file) return;

    setIsProcessing(true);
    try {
      const formData = new FormData();
      formData.append('file', file);
      formData.append('numScenes', numScenes.toString());

      // For now, we'll use a simple mock implementation
      // In production, this would call a server action to extract PDF text and use Gemini
      const mockScenes: Scene[] = Array.from({ length: numScenes }, (_, i) => ({
        index: i + 1,
        title: `Scene ${i + 1}`,
        description: 'Scene description will be generated by AI...',
        mood: 'Dramatic',
      }));

      setScenes(mockScenes);
      setStep('preview');
    } catch (err) {
      alert('Failed to generate scenes. Please try again.');
      console.error(err);
    } finally {
      setIsProcessing(false);
    }
  };

  const handleRegenerateScene = async (sceneIndex: number) => {
    // TODO: Regenerate individual scene using Gemini
    alert('Regenerate scene coming soon');
  };

  return (
    <div className="min-h-screen bg-gradient-to-b from-slate-900 to-slate-950 text-white py-8 px-4">
      <div className="max-w-4xl mx-auto space-y-8">
        {/* Header */}
        <div className="text-center space-y-3 mb-12">
          <h1 className="text-4xl font-bold gradient-text">📚 Memoir to Manga</h1>
          <p className="text-gray-400 text-lg">
            Upload your PDF memoir and we'll break it into cinematic scenes
          </p>
        </div>

        {/* Progress Steps */}
        <div className="flex items-center justify-between mb-12">
          {['upload', 'mapping', 'preview'].map((s, i) => (
            <div key={s} className="flex items-center flex-1">
              <div
                className={`w-10 h-10 rounded-full flex items-center justify-center font-bold transition-all ${
                  step === s
                    ? 'bg-plasma text-white shadow-lg scale-125'
                    : ['upload', 'mapping'].includes(s) && step === 'preview'
                    ? 'bg-green-600 text-white'
                    : 'bg-slate-700 text-gray-400'
                }`}
              >
                {['upload', 'mapping'].includes(s) && step === 'preview' ? '✓' : i + 1}
              </div>
              {i < 2 && (
                <div
                  className={`flex-1 h-1 mx-2 transition-all ${
                    step === 'preview' && i < 1
                      ? 'bg-green-600'
                      : step === 'preview' && i === 1
                      ? 'bg-plasma'
                      : 'bg-slate-700'
                  }`}
                />
              )}
            </div>
          ))}
        </div>

        {/* Step 1: Upload */}
        {step === 'upload' && (
          <div className="bg-gradient-to-br from-slate-800 to-slate-900 rounded-2xl p-8 border border-slate-700 space-y-6">
            <h2 className="text-2xl font-bold text-white">Step 1: Upload Your Memoir</h2>

            <div
              onClick={() => fileInputRef.current?.click()}
              className="border-2 border-dashed border-plasma/30 hover:border-plasma rounded-xl p-12 text-center cursor-pointer transition-all hover:bg-plasma/5"
            >
              <FileUp className="w-16 h-16 mx-auto text-plasma/50 mb-4" />
              <h3 className="text-xl font-bold text-white mb-2">
                {file ? file.name : 'Drop your PDF here'}
              </h3>
              <p className="text-gray-400 text-sm">
                {file
                  ? `File selected (${(file.size / 1024 / 1024).toFixed(2)} MB)`
                  : 'or click to browse'}
              </p>
              <input
                ref={fileInputRef}
                type="file"
                accept=".pdf"
                onChange={handleFileUpload}
                className="hidden"
              />
            </div>

            {file && (
              <button
                onClick={() => setStep('mapping')}
                className="w-full bg-plasma hover:bg-plasma/90 text-white font-bold py-3 rounded-lg flex items-center justify-center gap-2 transition-all"
              >
                Next: Configure Scenes <ChevronRight className="w-5 h-5" />
              </button>
            )}
          </div>
        )}

        {/* Step 2: Mapping */}
        {step === 'mapping' && (
          <div className="bg-gradient-to-br from-slate-800 to-slate-900 rounded-2xl p-8 border border-slate-700 space-y-6">
            <h2 className="text-2xl font-bold text-white">Step 2: Configure Scene Breakdown</h2>

            <div className="space-y-4">
              <div>
                <label className="text-white font-semibold mb-2 block">
                  How many scenes do you want?
                </label>
                <p className="text-sm text-gray-400 mb-4">
                  Each scene becomes one or more manga panels. Typical memoir: 8-12 scenes
                </p>

                <div className="flex items-center gap-4">
                  <input
                    type="range"
                    min="4"
                    max="24"
                    value={numScenes}
                    onChange={(e) => setNumScenes(parseInt(e.target.value))}
                    className="flex-1 h-2 bg-slate-700 rounded-lg cursor-pointer accent-plasma"
                  />
                  <div className="bg-plasma/20 border border-plasma/50 rounded-lg px-6 py-3 text-center">
                    <div className="text-3xl font-bold text-plasma">{numScenes}</div>
                    <div className="text-xs text-gray-400">scenes</div>
                  </div>
                </div>

                <div className="mt-6 p-4 bg-white/5 border border-white/10 rounded-lg">
                  <p className="text-sm text-gray-300">
                    <strong>📊 Estimated output:</strong>
                  </p>
                  <p className="text-xs text-gray-400 mt-2">
                    • {numScenes} scenes extracted from your memoir
                  </p>
                  <p className="text-xs text-gray-400">
                    • ~{numScenes * 2}-{numScenes * 3} manga panels to generate
                  </p>
                  <p className="text-xs text-gray-400">
                    • ~{Math.ceil((numScenes * 2.5 * 3) / 3)} credits needed (3 per panel)
                  </p>
                </div>
              </div>
            </div>

            <div className="flex gap-4">
              <button
                onClick={() => setStep('upload')}
                className="flex-1 bg-slate-700 hover:bg-slate-600 text-white font-bold py-3 rounded-lg transition-all"
              >
                ← Back
              </button>
              <button
                onClick={handleExtractAndGenerate}
                disabled={isProcessing}
                className="flex-1 bg-plasma hover:bg-plasma/90 disabled:bg-slate-600 text-white font-bold py-3 rounded-lg flex items-center justify-center gap-2 transition-all"
              >
                {isProcessing ? (
                  <>
                    <Loader2 className="w-5 h-5 animate-spin" />
                    Analyzing...
                  </>
                ) : (
                  <>
                    <Sparkles className="w-5 h-5" />
                    Generate Scenes
                  </>
                )}
              </button>
            </div>
          </div>
        )}

        {/* Step 3: Preview */}
        {step === 'preview' && (
          <div className="space-y-6">
            <div className="bg-gradient-to-br from-slate-800 to-slate-900 rounded-2xl p-8 border border-slate-700">
              <h2 className="text-2xl font-bold text-white mb-6">Step 3: Review Scenes</h2>
              <p className="text-gray-400 mb-6">
                Gemini AI has broken down your memoir into {scenes.length} scenes. Edit any
                scene or regenerate individually.
              </p>

              <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                {scenes.map((scene) => (
                  <div
                    key={scene.index}
                    className="bg-slate-700/50 border border-slate-600 rounded-xl p-4 space-y-3 hover:border-plasma/50 transition-all"
                  >
                    <div className="flex items-start justify-between">
                      <div>
                        <h3 className="text-white font-bold">Scene {scene.index}</h3>
                        <p className="text-xs text-gray-400">{scene.mood} mood</p>
                      </div>
                      <div className="bg-plasma/20 border border-plasma/50 rounded px-2 py-1">
                        <span className="text-xs text-plasma font-bold">#{scene.index}</span>
                      </div>
                    </div>

                    <p className="text-sm text-gray-300">{scene.description}</p>

                    <button
                      onClick={() => handleRegenerateScene(scene.index)}
                      className="text-xs text-plasma hover:text-plasma/80 font-semibold"
                    >
                      ↻ Regenerate Scene
                    </button>
                  </div>
                ))}
              </div>
            </div>

            <button className="w-full bg-gradient-to-r from-plasma to-bloom hover:from-plasma/90 hover:to-bloom/90 text-white font-bold py-4 rounded-xl text-lg transition-all shadow-lg">
              ✨ Start Generating Manga Panels
            </button>
          </div>
        )}
      </div>
    </div>
  );
}
